[package]
name = "docker-game-servers"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bollard = "0.11.0"
futures-util = "0.3.15"
tokio = { version = "1.8.0", features = ["full"] }
clap = "3.0.0-beta.2"
dirs = "3.0.2"
anyhow = "1.0.42"
comfy-table = "4.0.1"
termion = "1.5.6"
